---
title: Simple quadratic regression example
author: Carter Rees
date: '2017-10-28'
slug: simple-quadratic-regression-example
categories:
  - R
tags:
  - regression
---

The purpose of this post is to give an example of how to visualize a quadratic linear regression and also how to find the value's of the predictor variable which give you the min and max fitted values of your outcome of interest.

I was recently asked to look at relationships between server average query times and variables such as number of query counts, physical devices vs. AWS, disk utilization, number of nodes on a device, etc. The two main research questions were 1) what variables have significant associations with average query times and 2) what values of the predictor variables produce the mininmum average query times.

I like to start every project with simple methods. You can learn alot from descriptive statistics. If you remember your intro stats course from college there is a chance that
simple linear regression was taught in the descriptives section. An exmaple of using this method is below.
